###Recuperación de todas las clases
GET http://localhost:1234/classes/

###Creación de una clase
POST http://localhost:1234/classes
Content-Type: application/json

{
  "name": "Clase 3",
  "photo": "lkjhgfdslkjhgfds",
  "description": "Descripción de la clase 1",
  "maxCapacity": 10,
  "duration": 60,
  "instructorEmail": "instructor@instructor.instructor"
}
###hablar con dani sobre si se debería poder crear clases teniendo mismo nombre y mismo instructor