###Recuperación de todas las clases
GET http://localhost:1234/classes/

###Recuperación de una clase
GET http://localhost:1234/classes/0d5e5cb7-6efc-4fce-af04-322255e80e13

###Recuperación de todas las clases de un instructor
GET http://localhost:1234/classes/instructor/
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imluc3RydWN0b3JAaW5zdHJ1Y3Rvci5pbnN0cnVjdG9yIiwiZXhwIjoxNzEwOTE1NzA1NDM3LCJpYXQiOjE3MTAzMTA5MDV9.Xf7eLki6TVgGxBo9PZazdvWiRVzNiUrSodqp2mruSY8
###Recuperación de las clases en las que existe al menos 1 sesión gestionada por el instructor
GET http://localhost:1234/classes/sessions/
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imluc3RydWN0b3JAaW5zdHJ1Y3Rvci5pbnN0cnVjdG9yIiwiZXhwIjoxNzExOTA1NzQ3MDIxLCJpYXQiOjE3MTEzMDA5NDd9.ovtkrMYDB4c7o516GeKYoQgHDIf6BB1VS80RuwN24Pk
###Creación de una clase
POST http://localhost:1234/classes/
Content-Type: application/json

{
  "name": "Clase 3",
  "photo": "lkjhgfdslkjhgfds",
  "description": "Descripción de la clase 1",
  "maxCapacity": 10,
  "duration": 60,
  "instructorEmail": "instructor@instructor.instructor"
}

###Actualización de una clase
PUT http://localhost:1234/classes/
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imluc3RydWN0b3JAaW5zdHJ1Y3Rvci5pbnN0cnVjdG9yIiwiZXhwIjoxNzExNzk1NDA5MTM0LCJpYXQiOjE3MTExOTA2MDl9.AQijAcxlCDI56f4-PzASIEfWlE1CIedVmHEFH9zo7-I
Content-Type: application/json

{
  "UUIDClass": "7811333a-ca47-4e8b-9f8c-7e51855fa080",
  "name": "Clase 3",
  "photo": "insertePhoto :D",
  "description": "Descripción de la clase 4",
  "maxCapacity": 10,
  "duration": 60,
  "instructorEmail": "instructor@instructor.instructor"

}
