
### Response
GET http://localhost:1234/private
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiSmF2aUluVXNlIiwiZXhwIjoxNzA4MzczMzIzNzQ0LCJpYXQiOjE3MDgzNjk3MjN9.E3M3ElQjQslYZmxlMGbU_3e-50jU78qfiWAW0hKxwlE

### Users 

#### Get all users
GET http://localhost:1234/users
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmFkbWluIiwiZXhwIjoxNzEyMzExNjAyOTE1LCJpYXQiOjE3MTE3MDY4MDJ9.OceLwv5vDhtgeJmdyt-kyAh3idPrCbbEdI4nwqiMhck
#### Get all clients
GET http://localhost:1234/users/clients/
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmFkbWluIiwiZXhwIjoxNzEyMzExNjAyOTE1LCJpYXQiOjE3MTE3MDY4MDJ9.OceLwv5vDhtgeJmdyt-kyAh3idPrCbbEdI4nwqiMhck
### Get all admins,clients and instructors 
GET http://localhost:1234/users/all
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmFkbWluIiwiZXhwIjoxNzEyMzExNjAyOTE1LCJpYXQiOjE3MTE3MDY4MDJ9.OceLwv5vDhtgeJmdyt-kyAh3idPrCbbEdI4nwqiMhck
#### Login
POST http://localhost:1234/users/login
Content-Type: application/json

{
    "email": "admin@admin.admin"    ,
    "password": "admin123"
}
#### Register
POST http://localhost:1234/users/
Content-Type: application/json

{
    "email": "instructor@instructor.instructor",
    "password": "instructor123",
    "role": "I"
}

### Update user
PUT http://localhost:1234/users/
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmFkbWluIiwiZXhwIjoxNzA5OTIxNjczODYwLCJpYXQiOjE3MDkzMTY4NzN9.54oI7x7D9Lm2EXGixGX0t4rCYqmbS24U20IKewfHmJk
Content-Type: application/json

{
    "email": "instructor@instructor.instructor",
    "role": "I"
}
###Update client
PUT http://localhost:1234/users/clients/
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmFkbWluIiwiZXhwIjoxNzEyMzExNjAyOTE1LCJpYXQiOjE3MTE3MDY4MDJ9.OceLwv5vDhtgeJmdyt-kyAh3idPrCbbEdI4nwqiMhck
Content-Type: application/json

{
    "email": "client@client.client",
    "validated": "S"
}

### Delete user
DELETE http://localhost:1234/users/esUsuario@usuario.user
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmFkbWluIiwiZXhwIjoxNzA5OTIxNjczODYwLCJpYXQiOjE3MDkzMTY4NzN9.54oI7x7D9Lm2EXGixGX0t4rCYqmbS24U20IKewfHmJk      

### Get all instructors
GET http://localhost:1234/users/instructors/
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmFkbWluIiwiZXhwIjoxNzExNDY5NzA5NDQxLCJpYXQiOjE3MTA4NjQ5MDl9.OMlFgRBnpVnEajDpLY41LK55JJWVJqlYXGA3e-n19BU

### SEE IF A CLIENT IS VALIDATED
GET http://localhost:1234/users/clients/validation
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudEBjbGllbnQuY2xpZW50IiwiZXhwIjoxNzEzNzk1MTA0ODkyLCJpYXQiOjE3MTMxOTAzMDR9.zJNCaBg4l2iuZGgzevMoSXs3zDtXoUBdA4Th3hoEAwU